### ISSUE TITLE
2nd staticall intermodular call measuremets

### ISSUE THREAD

**Issue by ajsantander** [Synthetixio/synthetix-v3#110]
We want to know if getting the address of a module from the router with `STATICCALL` and doing `DELEGATECALL` is cheaper than the current mechanism.

**Comment by leomassazza** [comment]
As expected, using STATIC CALL to call a view/pure function doesn't make any difference in the gas usage since the compiler will use static call when the called function has the non-mutative functions. 

In order to do the test I updated the router generator and AnotherModule.sol to change the behavior. The changes were:
1- adding a "resolver" function called `GetModuleAddress` to the router populated with router generator.
2- update AnotherModule.setSomeValueOnSomeModule function to use Router.GetModuleAddress with a normal call
3- update AnotherModule.setSomeValueOnSomeModule function to use Router.GetModuleAddress with a static call

I made some measurements before step 1 (to have a baseline), after 1, after 2 and after 3.

The results are the following: 

### Baseline
  AnotherModule
    when writing to GlobalNamespace.someValue
      ✓ directly via SomeModule (36202 gas) (39ms)
      ✓ indirectly via AnotherModule (40826 gas) (54ms)


### After Step 1: Router with GetModuleAddress function, not used to verify the gas increment because the selector added to the router.
  AnotherModule
    when writing to GlobalNamespace.someValue
      ✓ directly via SomeModule (36269 gas) (41ms)
      ✓ indirectly via AnotherModule (40960 gas) (102ms)


### After Step 2: Router with GetModuleAddress function and using it with a normal call
  AnotherModule
    when writing to GlobalNamespace.someValue
      ✓ directly via SomeModule (36269 gas) (43ms)
      ✓ indirectly via AnotherModule (42081 gas) (54ms)

### After Step 3: Router with GetModuleAddress function and using it with a STATIC CALL
  AnotherModule
    when writing to GlobalNamespace.someValue
      ✓ directly via SomeModule (36269 gas) (39ms)
      ✓ indirectly via AnotherModule (42382 gas) (63ms)
