### ISSUE TITLE
CLI tests are not working with hardhat network on local machine

### ISSUE THREAD

**Issue by mjlescano** [Synthetixio/synthetix-v3#644]

**Comment by ajsantander** [comment]
@mjlescano they're not supposed to. They're intended to be run on the local network:
```
npx hardhat node
npx hardhat deploy --network local --clear --no-confirm --instance test
npm test
```

This is because we need the CLI and the test processes to both hit the same chain. The CLI tests start the CLI sub-process with child_process. If they both target the hardhat network, each starts its own, different hh network. This was discussed with Pato from Nomic Labs, and he said that the best solution is to use a local network.

If you want, I can try to throw a very explicit error if someone tries to run the tests on the hh network. I could also try to wrap these commands in a single npm test command.

**Comment by mjlescano** [comment]
What do you think of skipping the tests if using the `hardhat` network? This way, the `npm run test` command on the root of the project would still work.
