### ISSUE TITLE
Consider using arrays instead of mappings for tracking data indexed by epoch

### ISSUE THREAD

**Issue by ajsantander** [Synthetixio/synthetix-v3#916]
See this comment https://github.com/Synthetixio/synthetix-v3/pull/913#discussion_r863027731

This could actually apply to ElectionStorage elements as well.

**Comment by dbeal-eth** [comment]
i typically like to use an array because the purpose/use of storage slots in the data structure is made more obvious for a reader of the code. Since in this case, every election is just an incrementing id and there are no gaps or , an array is a natural choice for storage. As you suspected, I wasn't considering efficiency with the suggestion.

however, is `mapping(uint => someType) items;` ? I always imagined arrays were stored contiguously in storage so that there is no need to `kecak` when accessing an entry. I couldn't find a source either confirming or contradicting this, however.

**Comment by ajsantander** [comment]
Yes, mappings and arrays are pretty much the same for Solidity. See https://docs.soliditylang.org/en/v0.8.0/internals/layout_in_storage.html?highlight=storage#mappings-and-dynamic-arrays

Basically, elements on a mapping are stored at `keccak256(k . p)`, where p is the storage slot of the mapping/array, and stores the length of the array in the latter case, and k is the key of the element.

**Comment by ajsantander** [comment]
But yeah, I think we are good to go to change to arrays if what we choose to favor is code clarity over performance here. Happy to make the change. Adding this to the next spring. Thanks db :pray:
